---
abstract: unknown
author:
  - 'A S Lewis <aslewis@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '6.52'
  File::ShareDir::Install: '0'
  Path::Tiny: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.62, CPAN::Meta::Converter version 2.150010'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Games-Axmud
no_index:
  directory:
    - t
    - inc
    - share/plugins
requires:
  Archive::Extract: '0'
  Archive::Tar: '0'
  Archive::Zip: '0'
  Compress::Zlib: '0'
  Encode: '0'
  Fcntl: '0'
  File::Basename: '0'
  File::Copy: '0'
  File::Copy::Recursive: '0'
  File::Fetch: '0'
  File::Find: '0'
  File::HomeDir: '0'
  File::Path: '0'
  File::ShareDir: '0'
  File::ShareDir::Install: '0'
  Glib: '0'
  GooCanvas2: '0'
  Gtk3: '0'
  HTTP::Tiny: '0'
  IO::Socket::INET: '0'
  IPC::Run: '0'
  JSON: '0'
  Math::Round: '0'
  Math::Trig: '0'
  Module::Load: '0'
  Net::OpenSSH: '0'
  POSIX: '0'
  Regexp::IPv6: '0'
  Safe: '0'
  Scalar::Util: '0'
  Socket: '0'
  Storable: '0'
  Symbol: '0'
  Time::HiRes: '0'
  Time::Piece: '0'
  perl: '5.008'
resources:
  bugtracker: https://github.com/axcore/axmud/issues
  homepage: https://axmud.sourceforge.io/
  repository: https://github.com/axcore/axmud.git
version: v2.0.0
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
